version: '3.7'
networks:
  default:
    external:
      name: infra
services:
  nginx:
    image: "nginx:${TAG_NGINX}"
    container_name: nginx
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./nginx/conf.d:/etc/nginx/conf.d:ro
     - ./nginx/html:/usr/share/nginx/html:ro
     - ./nginx/htpasswd:/usr/share/nginx/htpasswd:ro
     - ./selenoid/video:/usr/share/nginx/video:rw
    ports:
     - "80:80"
    depends_on:
     - "selenium-hub"
    restart: always
  ftp:
    image: qaprosoft/pure-ftpd:latest
    env_file:
     - variables.env
    volumes:
    - $PWD/selenoid/video:/usr/share/ftp:rw
    ports:
     - "21:21"
     - "30000-30009:30000-30009"
    restart: always
  selenium-hub:
    image: qaprosoft/selenium-hub:3.5.1
    env_file:
     - variables.env
#    environment:
#     - JAVA_OPTS=-Dselenium.LOGGER.level=FINEST
    ports:
     - 4446:4444
    restart: always
  ggr:
    image: aerokube/ggr:latest-release
    volumes:
      - ./grid-router/:/etc/grid-router:ro
    ports:
     - "4444:4444"
    restart: always
  selenoid:
    networks:
      default: null
    image: aerokube/selenoid:latest-release
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/selenoid/:/etc/selenoid/
      - $PWD/selenoid/video/:/opt/selenoid/video/
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid/video/
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-timeout", "3m0s", "-container-network", "infra"]
    restart: always
