version: '3.7'
networks:
  default:
    external:
      name: infra
services:
  ggr:
    image: "aerokube/ggr:${TAG_GGR}"
    container_name: ggr
    volumes:
     - ./grid-router/:/etc/grid-router:ro
    ports:
     - "4444:4444"
    restart: always
  selenoid:
    networks:
      default: null
    image: aerokube/selenoid:${TAG_SELENOID}
    container_name: selenoid
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./selenoid/:/etc/selenoid/
     - ./selenoid/video/:/opt/selenoid/video/
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/hub/selenoid/video/
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-timeout", "3m0s", "-container-network", "infra"]
    restart: always
